name: aliyun

on:
  schedule:
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  signin:
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          DO_NOT_REWARD: "false"
          PUSH_TYPES: "PushPlus"
          REFRESH_TOKENS: ${{ secrets.ALI_TOKEN }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
